#!/bin/bash

PATH_WEB="/application";

cd $PATH_WEB/ngen_basic

function update_parameters_yml {
        echo "Checking for configuration files"
        cp /application/ngen_basic/src/NgenBundle/Docker/docker-build/final/files/parameters.yml /application/ngen_basic/app/config/parameters.yml
        sed  -i 's/$DB_SECRET/'"$(echo $RANDOM -d|sha256sum| awk '{print $1}')"'/'  /application/ngen_basic/app/config/parameters.yml
 }

function update_php_ini {
          echo "date.timezone=${DATE_TZ}" > /usr/local/etc/php/php.ini
          echo "upload_max_filesize =${UPLOAD_MAX}" >> /usr/local/etc/php/php.ini
          echo "post_max_size = ${POST_MAX}" >> /usr/local/etc/php/php.ini
          echo "memory_limit = ${MEMORY_LIMIT}" >> /usr/local/etc/php/php.ini
}
update_parameters_yml
update_php_ini

php bin/console cert_unlp:message:telegram:send
php bin/console cert_unlp:message:email:send
php bin/console swiftmailer:spool:send
php bin/console cert_unlp:network:update:host --max 100
