#!/bin/bash

PATH_WEB="/application";

cd $PATH_WEB/ngen_basic

bash /usr/local/bin/update_parameters

rm -rf app/logs/* app/cache/*;
mkdir -p app/cache app/logs
chmod  g+w app/cache app/logs
until x=$(php bin/console doctrine:schema:validate 2>/dev/null|grep "[OK]");do
  echo "Base no disponible esperando para comenzar la app"
  sleep 1
done;

if php bin/console doctrine:query:sql "SELECT * FROM INFORMATION_SCHEMA.TABLES"|grep incident
then
 echo "base ya creada"
else
 # La base no existe inserto la primer version
 echo "Instalando base inicial"
 php bin/console doctrine:database:import /root/base.inicial.sql
 php bin/console fos:elastica:populate --no-reset --env prod
fi;

# La base si existe aplica las migraciones que pudieran existir
php bin/console doctrine:migrations:migrate --no-interaction


#Estos 10 segundos son porque el elastic demora
sleep 10
if [[ ! -z "${POPULATE}" ]]; then
	php bin/console fos:elastica:populate --no-reset --env prod
	chown www-data -R $PATH_WEB/ngen_basic/app/Resources/app/Resources/feed/ $PATH_WEB/ngen_basic/app/Resources/incident
fi
php bin/console cache:clear --env=prod --no-debug
echo "por hacer assets:dump"
php bin/console assetic:dump --env=prod --no-debug
echo "por hacer assets:install"
php bin/console assets:install --symlink --env=prod
ln -s $PATH_WEB/ngen_basic/vendor/fortawesome/font-awesome/webfonts web/webfonts
chown www-data -R $PATH_WEB/ngen_basic/ngen_basic/var/sessions 
chown www-data -R $PATH_WEB/ngen_basic/ngen_basic/var/logs 
chown www-data -R $PATH_WEB/ngen_basic/ngen_basic/var/cache 
exec "$@"
