language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION='2.3.*'
        - php: 5.6
          env: SYMFONY_VERSION='2.7.*'
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true

install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - composer install --no-interaction --prefer-source

script: phpunit --coverage-text --colors

notifications:
  email:
    - support@cert.unlp.edu.ar
