language: php

php:
    - 7.2

matrix:
    include:
        -   php: 7.2
            env: SYMFONY_VERSION='2.8.*'
    allow_failures:
        -   php: nightly
        -   php: hhvm
    fast_finish: true

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-source

script: phpunit --coverage-text --colors

notifications:
    email:
        - support@cert.unlp.edu.ar
