apiVersion: 1

datasources:
  - name: Elastic Incidentes
    type: elasticsearch
    editable: true
    access: proxy
    database: "incidents_prod*"
    url: http://elasticsearch:9200
    jsonData:
      timeField: "createdAt"
