{
 "title": "Incidentes Externos",
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filtro", "label": "Agregar nuevo filtro" }
  ]
 },
 "panels": [
  {
   "title": "Incidentes Undefined",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1155",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1153", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false AND state:\"Undefined\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Staging",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1207",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1205", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false  AND state:\"Staging\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Abiertos",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1359",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1357", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false AND state:\"Open\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Cerrados",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1411",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1409", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false AND state:\"Closed\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Eliminados",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1513",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1511", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false  AND state:\"Removed\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Cerrados Por Inactividad",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1565",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1563", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false AND state:\"Closed by inactivity\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes por dia por entidad",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1617",
       "fake": true,
       "field": "network_data.networkEntity",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1618",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1615", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes por entidad (top 20) por dia",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1649",
       "fake": true,
       "field": "network_data.networkEntity",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1650",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1647", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes externos",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "createdAt", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:false",
     "timeField": "createdAt"
    }
   ]
  }
 ]
}