{
 "title": "Incidentes internos",
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filtro", "label": "Agregar nuevo filtro" }
  ]
 },
 "panels": [
  {
   "title": "Incidentes por mes por dependencia",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:97",
       "fake": true,
       "field": "network_data.networkEntity",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:98",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1w", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:95", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes por dia por tipo en 2 meses",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:157",
       "fake": true,
       "field": "type",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:158",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:155", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Undefined",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:291",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:289", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true AND state:\"Undefined\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Staging",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:346",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:344", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true AND state:\"Staging\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Abiertos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:401",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:399", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true AND state:\"Open\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Cerrado Por Inactividad",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:456",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:454", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true AND state:\"Closed by inactivity\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Cerrados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:564",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:562", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true AND state:\"Closed\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Eliminados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:619",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:617", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true AND state:\"Removed\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes por dia por dependencia en 2 meses",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:203",
       "fake": true,
       "field": "network_data.networkEntity",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:204",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:201", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes por dia por feed ultimo mes",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:675",
       "fake": true,
       "field": "feed",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:676",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:673", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes internos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1071",
       "field": "createdAt",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1069", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network_data.internal:true",
     "timeField": "createdAt"
    }
   ]
  }
 ]
}