<?php

namespace CertUnlp\NgenBundle\Entity;

/**
 * IncidentReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentReportRepository extends \Doctrine\ORM\EntityRepository
{
}
