<?php

/*
 * This file is part of the Ngen - CSIRT Incident Report System.
 *
 * (c) CERT UNLP <support@cert.unlp.edu.ar>
 *
 * This source file is subject to the GPL v3.0 license that is bundled
 * with this source code in the file LICENSE.
 */

namespace CertUnlp\NgenBundle\Repository;

use CertUnlp\NgenBundle\Entity\Network\NetworkElement;

/**
 * NetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostRepository extends NetworkElementRepository
{
    public function findOneByAddress(array $params): ?NetworkElement
    {

        $address = explode('/', $params['address']);
        switch (NetworkElement::guessType($address[0])) {
            case FILTER_FLAG_IPV4:
                return $this->findOneBy(['ip' => $address[0]]);
                break;
            case FILTER_FLAG_IPV6:
                return $this->findOneBy(['ip' => $address[0]]);
                break;
            case FILTER_VALIDATE_DOMAIN:
                return $this->findOneBy(['domain' => $address[0]]);
                break;
            default:
                return null;
        }

    }
}
