<?php

namespace CertUnlp\NgenBundle\Repository;

/**
 * IncidentDecisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentDecisionRepository extends \Doctrine\ORM\EntityRepository
{
}
