<?php

namespace CertUnlp\NgenBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IncidentDecisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidentDecisionRepository extends EntityRepository
{
    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @return object|null
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        $decision = null;
        if (isset($criteria['type'], $criteria['feed'])) {
            $decision = parent::findOneBy(array('feed' => $criteria['feed'], 'type' => $criteria['type'], 'network' => $criteria['network'] ?? null));
        }
        if (!$decision && isset($criteria['type']) && !isset($criteria['feed'])) {
            $decision = parent::findOneBy(array('feed' => 'undefined', 'type' => $criteria['type'], 'network' => $criteria['network'] ?? null));
        }
        if (!$decision && !isset($criteria['type']) && isset($criteria['feed'])) {
            $decision = parent::findOneBy(array('feed' => $criteria['feed'], 'type' => 'undefined', 'network' => $criteria['network'] ?? null));
        }
        if (!$decision && isset($criteria['network'])) {
            $decision = parent::findOneBy(array('feed' => 'undefined', 'type' => 'undefined', 'network' => $criteria['network']));
        }
        if (!$decision) {
            $decision = parent::findOneBy(array('feed' => 'undefined', 'type' => 'undefined', 'network' => null));
        }
        return $decision;
    }
}