<?php

namespace CertUnlp\NgenBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IndicentPriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicentPriorityRepository extends EntityRepository
{
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        if (isset($criteria['urgency'], $criteria['impact'])) {
            return parent::findOneBy(array('urgency' => $criteria['urgency'], 'impact' => $criteria['impact']));
        }
        if (!isset($criteria['urgency'], $criteria['impact'])) {
            return parent::findOneBy(array('urgency' => 'undefined', 'impact' => 'undefined'));
        }
        return parent::findOneBy($criteria, $orderBy);
    }
}
