<?php

namespace CertUnlp\NgenBundle\Repository;

/**
 * IndicentPriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicentPriorityRepository extends \Doctrine\ORM\EntityRepository
{
}
