parameters:
    database_host: $DB_HOST
    database_port: $DB_PORT
    database_name: $DB_NAME
    database_user: $DB_USER
    database_password: $DB_PASSWORD
    mailer_transport: $MAILER_TRANSPORT
    mailer_host: $MAILER_HOST
    mailer_user: $MAILER_USER
    mailer_password: $MAILER_PASSWORD
    mailer_sender: $MAILER_SENDER
    mailer_port: $MAILER_PORT
    mailer_encryption: $MAILER_ENCRYPTION
    secret: $DB_SECRET
    default_network: $DEFAULT_NETWORK
    team_mail: $TEAM_MAIL
    team_abuse: $TEAM_ABUSE
    team_url: $TEAM_URL
    team_name: $TEAM_NAME
    team_site: $TEAM_SITE
    team_logo: $TEAM_LOGO
    ngen_sign: $NGEN_SIGN
    ngen_lang: $NGEN_LANG
    session_max_idle_time: $SESSION_TIMEOUT
    elastic_host: $ELASTIC_HOST
    elastic_port: $ELASTIC_PORT
    # Options {localhost:993/imap/ssl/novalidate-cert}INBOX {localhost:143}INBOX
    imap_server: $IMAP_SERVER
    imap_username: $IMAP_USERNAME
    imap_password: $IMAP_PASSWORD
    external_dashboard_grafana: $EXTERNAL_DASHBOARD_GRAFANA
    internal_dashboard_grafana: $INTERNAL_DASHBOARD_GRAFANA
