{
 "title": "Incidentes internos",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filtro", "label": "Agregar nuevo filtro" }
  ]
 },
 "panels": [
  {
   "title": "Incidentes por mes por dependencia",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "network.networkEntity.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "createdAt", "id": "2", "settings": { "interval": "1w", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes por dia por tipo en 2 meses",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "type.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "createdAt", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Undefined",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "createdAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\" AND state.slug:\"undefined\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Staging",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "createdAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\" AND state.slug:\"staging\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Abiertos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "createdAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\" AND state.slug:\"open\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Cerrado Por Inactividad",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "createdAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\" AND state.slug:\"closed_by_inactivity\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Cerrados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "createdAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\" AND state.slug:\"closed\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes Eliminados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "createdAt", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\" AND state.slug:\"removed\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes por dia por dependencia en 2 meses",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "network.networkEntity.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "createdAt", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes por dia por feed ultimo mes",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "feed.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "createdAt", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\"",
     "timeField": "createdAt"
    }
   ]
  },
  {
   "title": "Incidentes internos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "createdAt", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "network.discr:\"internal\"",
     "timeField": "createdAt"
    }
   ]
  }
 ]
}